apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uxnn1i1-z-python 
  janus-idp.io/tekton: uxnn1i1-z-python
  backstage.io/kubernetes-id: uxnn1i1-z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxnn1i1-z-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  