apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uxnn1i1-z-python
  janus-idp.io/tekton: uxnn1i1-z-python
  backstage.io/kubernetes-id: uxnn1i1-z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxnn1i1-z-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
